### ISSUE TITLE
Increase minimum iris size

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#15]
[Overview](https://github.com/biometricITC/Eye-Toolbox/blob/master/EYE_Toolbox_Overview.adoc) _suggests_ (or maybe requires, depending on #9) a minimum iris diameter of 75 pixels. ISO/IEC 29794-6 _requires_ a minimum iris diameter of 160 pixels. I suggest we mimic the requirements from ISO.

**Comment by woodbe** [comment]
I agree, I'm good with going higher.

**Comment by n-kai** [comment]
I also agree
