### ISSUE TITLE
Iris toolbox and curved PAI

### ISSUE THREAD

**Issue by woodbe** [biometricITC/Eye-Toolbox#18]
In the toolbox I created biometricITC/cPP-biometrics#139 I had some tests using a contact lens to add some level of curvature to the iris pattern. While I was looking at the FIDO documentation they do not list a contact lens but do make mention of using something like a doll's eye (or I guess you could try something like a ping pong ball), and placing the image over that surface.

The one successful attack (at least that has been published) against the Samsung iris sensor used a contact lens, which is why I focused on that, and I'm not sure how successful the stretching would be in placing the image onto a round object (I'm thinking wrinkles in the paper, though I guess it depends on how much curve you go for).

What are thoughts about one vs the other or whether or both? My concern is the total number of tests (I already have a lot, though some probably will go away), but this is a place I don't have a really good feel about.

**Comment by nils-tekampe** [comment]
I also could not yet read all the contribution completely but would like to bring up a general and important question:
How many of the artefacts presented to the TOE have to be recognized by the TOE correctly? 

My opinion: The toolboxes contain the "state of the art" of what PAD systems shall recognize and I would not allow big error rates here. My expectation would basically be that all the PAI from the toolbox are reproducibly recognized by the system (whatever that means in concrete numbers). 

Any thoughts?

**Comment by n-kai** [comment]
@woodbe I agree with you. It seems that there is no papers that report successful attacks using e-ink devices (the paper (https://arxiv.org/pdf/1804.00194.pdf) just mentions that e-ink devices could be used for the attack without any experiments)

**Comment by woodbe** [comment]
Closing at this time, it will be available in the history of closed issues related to the eye toolbox.
