### ISSUE TITLE
Eye 05-01 and Eye 05-02 in Mobile Toolbox for Eye Verification List

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Eye-Toolbox#2]
Eye 05-01 and Eye 05-02 (both tests use T.1b (Night-mode camera)) are assigned to **Visible** only. I think that they should also be assigned to **IR/NIR**.

Title of both test should also be changed (e.g. Eye, printed photo attack with contact lens -> Eye, IR/NIR printed photo attack with contact lens)

My patch (NK-patch-5) corrects this issue but I want Brian to confirm that this is right correction or not.

**Comment by woodbe** [comment]
Closed based on update.
