### ISSUE TITLE
Use of "SNS/internet"

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#5]
I was unsure as to the definition of "SNS" in "SNS/internet" as used in the overview. After further reading, I believe this means _Social Networking Site_. It is later referred to as "social media." I would suggest SNS be spelled out or removed in favor of _any_ image source on the Internet (e.g., image search, dating profile, conference speaker bio, news clip, etc.)

**Comment by n-kai** [comment]
I agree with @gfiumara
