### ISSUE TITLE
Specifications for lighting during enrollment

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#6]
In Overview:

> The evaluator shall enroll test users’ eyes under the controlled environment where the background of the scene is uniform, the light in the room is switched on, and the window blinds are down (i.e., direct external lighting is blocked).

Are there recommendations on the type, color temperature, etc. of light to be used?

**Comment by n-kai** [comment]
Researchers normally enroll users under the controlled environment but they didn't describe any detail information like color temperature in the research papers. So the evaluator may simply follow the above general guidance if the evaluator can't find more specific recommendations in relevant research papers.

**Comment by woodbe** [comment]
What I've heard from my team is that it is usually more about consistency than any specific details such as the color.

**Comment by gfiumara** [comment]
Okay. Since identical environments are already specified for both enrollment and artifact presentation, I suggest we close this issue without action.

**Comment by woodbe** [comment]
I'm OK with that, @n-kai any concerns?

**Comment by n-kai** [comment]
I don't have any concern please close
