### ISSUE TITLE
Type 1/2 vs. Normal/High Quality

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#7]
The overview refers to two types of tools/artefacts: "normal" and "high" quality. In the attacks section, these two types are referred to as Type 1 and Type 2. We should standardize on nomenclature. My vote would be for Type 1 and Type 2, such that they do not have to be renamed when a high**er** quality tool presents itself.

**Comment by n-kai** [comment]
I agree with @gfiumara (I think that face toolbox should also be modified)
