### ISSUE TITLE
High Quality Tool Newness: Should or Shall?

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#8]
In overview (emphasis mine):

> Such tools **should** be the latest available (i.e., released at least within one year from the date of PAD testing, or as recent as possible depending on the type of device)

In Inventory, this _should_ becomes a _shall_ in a few spots (emphasis mine):

> New dSLR **shall** be purchasable at the date of testing and the camera was released within 1 year from the date of testing.

> The evaluator **shall** use the highest resolution screen that was released within 1 year from the date of testing.

Which should it be? My vote would be for _shall_.

**Comment by n-kai** [comment]
I agree with shall.
